projects:
  EmployeeSkills:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-west-2
        apiId: jeign2eshff2leixfp4cherioy
        maxDepth: 2
extensions:
  amplify:
    version: 3
